// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `detect_format`, `intermediate_to_rgb8`

/// Probe a RAW file to extract metadata without full decode.
///
/// This reads only the file header and EXIF data — fast enough for
/// gallery thumbnails and format detection.
RawImageInfo probeRaw({required List<int> fileBytes}) =>
    RustLib.instance.api.crateApiDecoderProbeRaw(fileBytes: fileBytes);

/// Decode a RAW file to 8-bit sRGB pixel data.
///
/// Performs full Bayer demosaic, white balance, color space conversion,
/// and gamma correction. Returns packed RGB bytes (3 bytes per pixel,
/// row-major, no padding).
RawDecodeResult decodeRaw({required List<int> fileBytes}) =>
    RustLib.instance.api.crateApiDecoderDecodeRaw(fileBytes: fileBytes);

/// Decode a RAW file and return it as JPEG bytes.
///
/// Convenience function that decodes, then JPEG-compresses the result.
/// Useful when the caller wants to feed the image into Flutter's
/// `instantiateImageCodec` which handles JPEG natively.
Uint8List decodeRawToJpeg({
  required List<int> fileBytes,
  required int quality,
}) => RustLib.instance.api.crateApiDecoderDecodeRawToJpeg(
  fileBytes: fileBytes,
  quality: quality,
);

/// Extract the embedded JPEG preview/thumbnail from a RAW file.
///
/// Most RAW files contain an embedded full-size JPEG preview that was
/// generated by the camera. This is much faster than full decode and
/// is suitable for gallery display.
Uint8List? extractPreview({required List<int> fileBytes}) =>
    RustLib.instance.api.crateApiDecoderExtractPreview(fileBytes: fileBytes);

/// Check if a file's bytes look like a supported RAW format.
bool isSupportedRaw({required List<int> fileBytes}) =>
    RustLib.instance.api.crateApiDecoderIsSupportedRaw(fileBytes: fileBytes);

/// Result of decoding a RAW file to RGB pixels.
class RawDecodeResult {
  /// Decoded pixel data as 8-bit sRGB (RGBRGBRGB..., no alpha).
  final Uint8List pixels;

  /// Image width after demosaic and orientation.
  final int width;

  /// Image height after demosaic and orientation.
  final int height;

  /// Camera make.
  final String make;

  /// Camera model.
  final String model;

  /// ISO sensitivity.
  final int iso;

  const RawDecodeResult({
    required this.pixels,
    required this.width,
    required this.height,
    required this.make,
    required this.model,
    required this.iso,
  });

  @override
  int get hashCode =>
      pixels.hashCode ^
      width.hashCode ^
      height.hashCode ^
      make.hashCode ^
      model.hashCode ^
      iso.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawDecodeResult &&
          runtimeType == other.runtimeType &&
          pixels == other.pixels &&
          width == other.width &&
          height == other.height &&
          make == other.make &&
          model == other.model &&
          iso == other.iso;
}

/// Metadata extracted from a RAW file before full decode.
class RawImageInfo {
  /// Image width in pixels.
  final int width;

  /// Image height in pixels.
  final int height;

  /// Camera make (e.g. "Canon", "Nikon", "Sony").
  final String make;

  /// Camera model (e.g. "EOS R5", "Z 9", "A7R V").
  final String model;

  /// ISO sensitivity.
  final int iso;

  /// Whether the format is supported for full decode.
  final bool supported;

  /// Detected RAW format name (e.g. "DNG", "CR3", "NEF", "ARW").
  final String format;

  const RawImageInfo({
    required this.width,
    required this.height,
    required this.make,
    required this.model,
    required this.iso,
    required this.supported,
    required this.format,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      make.hashCode ^
      model.hashCode ^
      iso.hashCode ^
      supported.hashCode ^
      format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawImageInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          make == other.make &&
          model == other.model &&
          iso == other.iso &&
          supported == other.supported &&
          format == other.format;
}
